[package]
name = "llamacpp"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "llamacpp"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.30.0"
llama_cpp_rs = {version = "0.3.0"}
